[package]
name = "hello-world"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }

[[bin]]
name = "hello-world"
path ="main.rs"
test = false
bench = false